--UNIDADE FEDERATIVA
CREATE TABLE UNIDADE_FEDERATIVA 
(
  ID NUMBER NOT NULL 
, SIGLA VARCHAR2(2) NOT NULL 
, NOME VARCHAR2(100) NOT NULL 
, CONSTRAINT UNIDADE_FEDERATIVA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE UNIDADE_FEDERATIVA_SEQ INCREMENT BY 1 START WITH 1;

-- MUNICIPIO

CREATE TABLE MUNICIPIO 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(120) NOT NULL 
, ID_UNIDADE_FEDERATIVA NUMBER NOT NULL 
, CONSTRAINT MUNICIPIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE INDEX MUN_UNID_FED_IND on MUNICIPIO(ID_UNIDADE_FEDERATIVA);

ALTER TABLE MUNICIPIO
ADD FOREIGN KEY (ID_UNIDADE_FEDERATIVA) 
REFERENCES UNIDADE_FEDERATIVA(ID);

CREATE SEQUENCE MUNICIPIO_SEQ INCREMENT BY 1 START WITH 1;


-- PESSOA
CREATE TABLE PESSOA 
(
  ID NUMBER NOT NULL 
, ID_MUNICIPIO NUMBER 
, CONSTRAINT PESSOA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE INDEX PES_MUN_IND on PESSOA(ID_MUNICIPIO);

ALTER TABLE PESSOA
ADD FOREIGN KEY (ID_MUNICIPIO) 
REFERENCES MUNICIPIO(ID);

CREATE SEQUENCE PESSOA_SEQ INCREMENT BY 1 START WITH 1;

--PESSOA FISICA

CREATE TABLE PESSOA_FISICA 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR(150) NOT NULL
, DATA_NASCIMENTO DATE NOT NULL
, CONSTRAINT PESSOA_FISICA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PESSOA_FISICA
ADD FOREIGN KEY (ID) 
REFERENCES PESSOA(ID);

-- PESSOA JURIDICA

CREATE TABLE PESSOA_JURIDICA 
(
  ID NUMBER NOT NULL 
, RAZAO_SOCIAL VARCHAR(150) NOT NULL
, DATA_FUNDACAO DATE NOT NULL
, CONSTRAINT PESSOA_JURIDICA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PESSOA_JURIDICA
ADD FOREIGN KEY (ID) 
REFERENCES PESSOA(ID);

--TIPO DEPENDENCIA
CREATE TABLE TIPO_DEPENDENCIA 
(
  ID NUMBER NOT NULL 
, DESCRICAO VARCHAR2(50) NOT NULL 
, CONSTRAINT TIPO_DEPENDENCIA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE TIPO_DEPENDENCIA_SEQ INCREMENT BY 1 START WITH 1;


-- DEPENDENCIA PESSOA

CREATE TABLE DEPENDENCIA_PESSOA 
(
  ID NUMBER NOT NULL 
, ID_TIPO_DEPENDENCIA NUMBER NOT NULL 
, ID_DEPENDENTE NUMBER NOT NULL 
, ID_DEPENDENTE_DE NUMBER NOT NULL
, CONSTRAINT DEPENDENCIA_PESSOA PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE INDEX DEP_PES_TP_DEP_IND on DEPENDENCIA_PESSOA(ID_TIPO_DEPENDENCIA);
CREATE INDEX DEP_DEPENDENTE_IND on DEPENDENCIA_PESSOA(ID_DEPENDENTE);
CREATE INDEX DEP_DEPENDENTE_DE_IND on DEPENDENCIA_PESSOA(ID_DEPENDENTE_DE);


ALTER TABLE DEPENDENCIA_PESSOA
ADD FOREIGN KEY (ID_TIPO_DEPENDENCIA) 
REFERENCES TIPO_DEPENDENCIA(ID);

ALTER TABLE DEPENDENCIA_PESSOA
ADD FOREIGN KEY (ID_DEPENDENTE) 
REFERENCES PESSOA_FISICA(ID);

ALTER TABLE DEPENDENCIA_PESSOA
ADD FOREIGN KEY (ID_DEPENDENTE_DE) 
REFERENCES PESSOA_FISICA(ID);

CREATE SEQUENCE DEPENDENCIA_PESSOA_SEQ INCREMENT BY 1 START WITH 1;

-- VIEWS
-- PESSOA VW

create or replace view pessoa_vw as
select p.id, p.ID_MUNICIPIO, NVL(pf.nome,pj.RAZAO_SOCIAL) nome, NVL(pf.DATA_NASCIMENTO, pj.DATA_FUNDACAO) data_nascimento, decode(pf.id, null, 'J', 'F') tipo_pessoa
from PESSOA p, PESSOA_FISICA pf, PESSOA_JURIDICA pj
where pf.id (+) = p.id
and pj.id (+) = p.id;

